# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG TRINO_VERSION

FROM trinodb/trino:${TRINO_VERSION}

ARG RANGER_VERSION

USER root
# install sudo and allow trino user to use sudo without password
RUN microdnf update && microdnf install -y sudo && microdnf clean all && echo 'trino ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY ./dist/${RANGER_VERSION}.tar.gz /etc/trino
COPY ./scripts/trino/install.properties /etc/trino
COPY ./scripts/trino/reload_properties.sh /etc/trino

USER root
RUN cd /etc/trino && \
    mkdir -p /etc/trino/${RANGER_VERSION} && \
    tar xvf ${RANGER_VERSION}.tar.gz -C /etc/trino/${RANGER_VERSION} --strip-components 1 && \
    rm -rf ${RANGER_VERSION}.tar.gz && \
    cp /etc/trino/install.properties /etc/trino/${RANGER_VERSION}/ && \
    cp /etc/trino/reload_properties.sh /etc/trino/${RANGER_VERSION}/ && \
    chmod 0755 /etc/trino/${RANGER_VERSION}/reload_properties.sh

USER trino

ENTRYPOINT ["/bin/bash", "-cx"]
CMD ["sudo -E /etc/trino/${RANGER_VERSION}/reload_properties.sh && sudo -E /etc/trino/${RANGER_VERSION}/enable-trino-plugin.sh && /usr/lib/trino/bin/run-trino"]
